<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>sshweave</AssemblyName>
    <RootNamespace>SshWeave</RootNamespace>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <InvariantGlobalization>true</InvariantGlobalization>
    <IlcGenerateStackTraceData>true</IlcGenerateStackTraceData>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
